### ISSUE TITLE
Feature Request: Add option to browse album or artist returned by query

### ISSUE THREAD

**Issue by gregbreit** [AF-1/lms-contextstats#1]
## DESCRIBE THE BUG
When I click on an album title returned by a specific search (either from context menu or top-level), the options presented are "Play now", "Play next", and "Append to queue". It would be useful to have an option to browse the album (i.e. open it in the left-hand pane) to view its tracks. Similar issue with returned artists -- it would be helpful to be able to "browse" the artist, and see a list of their albums in the left-hand pane. Currently, the only options involve adding the results to the play queue.

<br><br>
## TO REPRODUCE

[home menu item enabled in settings]
1. Click on "My Music"-->"Context Stats"-->"Albums"
2. [example] Click on "Not Completely Rated"
3. Click on returned album title
4. Options presented are "Play now", "Play next", and "Append to queue". No option to "Browse".

or:

1. Click on "My Music"-->"Artists"
2. Open context menu for a particular artist
3. Click on "Albums sorted by statistics"
4. Click on returned album title
5. Options presented are "Play now", "Play next", and "Append to queue". No option to "Browse".

or (artist query):

1. Click on "My Music"-->"Context Stats"-->"Artists"
2. [example] Click on "Most Played"
3. Click on returned artist name
4. Options presented are "Play now", "Play next", and "Append to queue". No option to "Browse".

<br><br>
## EXPECTED BEHAVIOR
There should be an option to browse the album or artist returned by the query. Currently, the only available options involve adding the album or artist to the play queue. 

<br><br>
## VERSION INFO
* LMS version: 8.5.2
* OS (version): piCore - EN - utf8
* Plugin version: Context Stats 0.1.8
* Web skin/controller: Material Skin 5.0.4
* Browser (version): Safari 17.5 (Mac OS 14.5; iOS 17.5.1)

<br><br>
## ADDITIONAL CONTEXT
Example of how this would help me: I wish to find unrated or not completely rated albums in my library and rate them. I have used TrackStat in the past for this, and would like to do this with Context Stats now that it replaces most (all?) of the functionality of Erland's old plugin. Ideally, I would bring up the list of "Not completely rated" albums and open a returned album in the browse pane. Then I can quickly add ratings from the context menu for an individual track or the entire album.

I can do this with the Context Stats plugin as is, but it requires the extra steps of adding the album to the play queue, then clicking on the album title on one track in the queue to open that album in the browse pane. It would streamline my workflow to open a query result directly into the browse pane. Plus, if I'm listening to music while using your plugin, I would rather not alter the play queue in order to browse a query result. 

FYI, I am the guy (Greggy_Oakland) that asked about replicating the "Last Played Songs" query from TrackStat in the LMS forum. Thanks for pointing me to your plugin. I was a subscriber and regular user of Erland's plugins for years -- I appreciate all your efforts to pick up where he left off. Kudos to your work on Dynamic Playlists in particular.

**Comment by AF-1** [comment]
I've added a browse option in the latest release. I think this should do what you want.

**Comment by gregbreit** [comment]
Yes, it does that exactly. Thanks very much for the quick turnaround. It
makes the plugin much more usable for me.

I do have a non-urgent question/comment/suggestion regarding how you
calculate Play Count. Shall I submit a new issue on GitHub, or do you
prefer another avenue?

Thanks again for all your efforts.

Greg

**Comment by AF-1** [comment]
For some unknown reason, I don't get notified of any mention, quote, private message etc. on the LMS forum anymore. And I don't go there very often.
So just fire away and post your question here.
