### ISSUE TITLE
Artist and Album play counts may give unexpected results for "Most Played" queries

### ISSUE THREAD

**Issue by gregbreit** [AF-1/lms-contextstats#2]
## DESCRIBE THE BUG

The plugin computes play counts for tracks, albums, and artists. The play count for a track comprises the total number of times that track has been played, as expected. The play count for an *artist* appears to be the total number of artist track plays, divided (normalized) by the total number of library tracks for that artist. The play count for an *album* appears to be the total number of album track plays divided by the total number of album tracks.

In other words, the album or artist play counts represent how *completely* that album or artist has been played. Looks like this is the same thing as "Average Play Count" in the Visual Statistics plugin. [cool plugin btw]

**Especially in the case of artist play counts, this can cause distorted results when comparing artists with large vs. small numbers of library tracks**.
<br><br>
## TO REPRODUCE
1. Go to "My Music"-->"Context Stats"-->"Artists"-->"Most Played"
2. The list of "Most Played" artists is biased toward artists with few library tracks. The actual "most played" artists in my library do not even show up on the list.
<br><br>
## EXPECTED BEHAVIOR
I expected the artists I listen to the most to have the highest artist play count and appear near the top of the list.
<br><br>
## VERSION INFO
* LMS version: 8.5.2
* OS (version): piCore - EN - utf8
* Plugin version: 0.2.0
* Web skin/controller: Material Skin
* Browser (version): Safari 17.5, MacOS 14.5, iOS 17.5.1
<br><br>
## ADDITIONAL CONTEXT
Here's a somewhat extreme example from my library (approx. 100,000 tracks; 7,000 albums; 1,700 artists). 

Consider two artists in my library:

1) Wilco -- One of my favorite and most listened-to bands. 2822 library tracks between studio albums, box sets, live recordings, etc.
2) Fat Daddy -- Artist on Track 1 of "A John Waters Christmas", a compilation of stupid and kitschy holiday songs that gets played repeatedly around our house during the month of December. So, there is just *one* track by Fat Daddy in my entire library.

When I do a query for "Most Played" artists, I would expect to see Wilco near or at the top of the list since we listen to them frequently. But instead, the top artist is Fat Daddy with a PC=28.  Wilco's PC is 0.87, which doesn't put them anywhere near the top of the "Most Played" artist list. 

If I correctly understand your PC calculation, this means that since stats have been collected, I have played Fat Daddy 28 times (PC28 * 1 library track), and Wilco 2455 times (PC 0.87 * 2822 library tracks).  

In the case of a query for "Most Played" artist, **I think the absolute total number of track plays is a more meaningful metric** and would put Wilco near the top of my list where it belongs. 

The averaged calculation for *album* play counts is less of a problem. Querying "Most Played" albums returns a list that makes sense, although it does discriminate against albums with a high track count.  

I don't have TrackStat installed anymore, so I can't compare your query results to Erland's. However I suspect he used absolute total plays for all of his "Most Played" queries. I recall that searching for "Most Played" albums, artists, and tracks with TrackStat all returned results that made sense.

Anyway, my suggestion is to use absolute total track plays for all "Most Played" queries.

**Comment by gregbreit** [comment]
Quick followup -- Just tested your new options in Visual Statistics 1.7.4. "Artists with top total play count" and "Albums with top total play count" correctly produce the results I'm talking about in this issue. Thanks.

**Comment by AF-1** [comment]
As of 0.2.1, Most/Least Played lists use the total count, and lists using average counts are marked as such.

**Comment by gregbreit** [comment]
Verified. Thanks a lot.
